LeeDongu/merge_login/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/',signup, name='signup'), # 회원가입을 위한 url
    path('login/',login_check,name='login'), # 로그인 요청을 위한 url
    path('logout/',logout, name='logout'), # 로그아웃 요청을 위한 url
]

LeeDongu/merge_login/config/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # main url 등록
    path('',index), # http://127.0.0.1:8000
    # path('login/',login)
    # accounts 아래에 독립적으로 url 운영
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LeeDongu/merge_login/accounts/models.py
from django.db import models
from django.conf import settings    # 인증 관련 패키지 사용을 위한 import
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.


# 파일 저장 경로 설정 함수
def user_path(instance, filename):
    # instance : photo
    # filename : 업로드 된 파일 명
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)  # 무작위로 생성 된 8문자를 하나의 문자열로 생성
    extension = filename.split('.')[-1]  # 사용자가 올린 이밎파일명의 파일 확장자 선택
    return 'account/{}/{}.{}'.format(instance.user.username, pid, extension)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField('별명', max_length=20, unique=True)
    picture = ProcessedImageField(upload_to=user_path,  # upload 될 공간을 지정 (user_path라는 함수를 따로 구성해서 경로 생성 할 예정)
                                  processors=[ResizeToFill(150, 150)],  # upload된 image size를 150*150으로 조정
                                  format='JPEG',  # image 형식 설정
                                  options={'quality': 90},  # image의 품질 설정
                                  blank=True)
    about = models.CharField(max_length=300, blank=True)
    Gender = (
        ('선택암함', '선택안함'),
        ('여성', '여성'),
        ('남성', '남성'),
    )  # 일반 변수 - db 필드 사용되지 않음

    gender = models.CharField('성별(선택사항)',
                              max_length=10,
                              choices=Gender,
                              default='N')

    def __str__(self):
        return self.nickname

LeeDongu/merge_login/main/models.py
from django.db import models

# Create your models here.

LeeDongu/merge_login/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User

class LoginForm(forms.ModelForm) : # ModelForm - model을 기준으로 form 생성
    class Meta:
        model = User
        fields = ["username","password"]

class SignupForm(UserCreationForm) :
    # 문자 입력 필드를 생성 : 사용자명 입력칸 형태로 만들어짐
    username = forms.CharField(label='사용자명', widget=forms.TextInput(attrs={
        'pattern' : '[a-zA-Z0-9]+', # 생성되는 username은 대소문자와 숫자로만
        'title' : '특수문자, 공백 입력 불가'
    }))
    nickname = forms.CharField(label='닉네임') # 닉네임 입력 필드 생성
    picture = forms.ImageField(label='프로필 사진',required=False) # required = False -> 입력 안해도 된다는뜻
    # form과 관련된 class는 반드시 내부에 meta 클래스를 갖고 있어야 함
    class Meta(UserCreationForm.Meta) : # 상위 클래스 상속 받아 생성
        fields = UserCreationForm.Meta.fields + ('email',)
    # 장고는 UserCreationForm을 제공하며, 해당 form안에 username, password1, password2의 필수 필드와
    # email 등 선택 필드가 포함되어 있음 - Meta 구성해 놓으면 해당 필드를 그대로 사용 할 수 있음
    
    # 입력 내용의 유효성검사가 반드시 필요함
    # UserCreationForm이 제공 clean_필드명 메서드를 이용하면 간단하게 유효성 검사가 가능
    def clean_nickname(self):
        nickname = self.cleaned_data.get('nickname')
        # db에 동일한 nickname이 있는지 확인
        if Profile.objects.filter(nickname = nickname).exists() :
            raise forms.ValidationError('이미 존재하는 닉네임입니다.') # 에러 발생
        return nickname

    def clean_email(self):
        email=self.cleaned_data.get('email')
        User = get_user_model() # user모델 전부 가져와서 User변수에 저장 - user 모델은 장고가 내부적으로 제공하는 모델
        if User.objects.filter(email=email).exists() : # email이 존재하면
            raise forms.ValidationError('사용중인 이메일입니다.')
        return email
    
    def clean_picture(self): # 파일이 있는지 확인
        picture = self.cleaned_data.get('picture')
        if not picture :
            picture = None # 프로필 사진
        return picture
    
    def save(self):
        user=super().save() # User 모델에 먼저 저장
        Profile.objects.create( # Profile model에 create(insert 문과 같음)
            user=user,
            nickname = self.cleaned_data['nickname'],
            picture = self.cleaned_data['picture'],
        )
        return user

LeeDongu/merge_login/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login  # 로그인 기능을 하는 패키지 함수
from django.contrib.auth import logout as django_logout
from .forms import SignupForm, LoginForm  # forms.py를 생성해서 SignupForm, LoginForm  정의해야 함


# Create your views here.

# def login(request) :
#     return render(request, 'accounts/login.html')

def signup(request):  # 회원가입 요청에 의해 동작
    if request.method == 'POST':  # post 방식으로의 요청만 회원가입 절차를 수행
        # post 방식으로 데이터 전송의 경우에는 네트워크패킷(데이터)
        # 전송할 파일이 없을 경우 request.FILES는 빼도 됨
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():  # form에 유효한 데이터가 있으면 (값을 client가 정상적으로 전송했으면)
            # 사용자가 전송해준 회원가입 정보를 model을 통해서 db에 저장
            user = form.save()  # 회원가입 완료 - forms.py에서 db에 저장되도록 구성해야 함
            return redirect('accounts:login')  # accounts/login 으로 바로 연결
    else:  # GET 방식일 경우
        form = SignupForm()  # 회원가입폼을 다시 출력
    return render(request, 'accounts/signup.html', {'form': form})


def login_check(request):  # 로그인 요청에 의해 동작
    if request.method == "POST":
        form = LoginForm(request.POST)  # post로 넘어온 데이터 객체 반환
        name = request.POST.get('username')  # post로 넘어온 데이터 중 일부 반환
        pwd = request.POST.get('password')

        # user모델과 연동된 db테이블에 사용자가 있는지 확인
        user = authenticate(username=name, password=pwd)

        if user is not None:  # 인증 되었으면
            login(request, user)  # 로그인 진행 - 클라이언트 서버간에 세션을 연결
            return redirect("/")
        else:
            return render(request, 'accounts/login_fail.html')
    else:
        form = LoginForm()  # 잘못된 접근(get방식)
        return render(request, 'accounts/login.html', {"form": form})


def logout(request):
    django_logout(request)  # 기본 로그아웃 기능 사용 - 연결된 세션을 종료
    return redirect("/")

LeeDongu/merge_login/main/views.py
from django.shortcuts import render

# Create your views here.

def index(request) :
    return render(request,'main/index.html')

LeeDongu/merge_login/accounts/templates/accounts/layout.html
{% extends "layout.html" %}

LeeDongu/merge_login/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
      {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/login_layout.css' %}">
    <title></title>
  </head>
  <body>
    <div id="wrap">
        <div id="header">
            <div id="header_box">
                <a href="" class="header_img" id="log.naver"><img src="{% static 'image/d2_logo.png'%}"></a>
            </div>
        </div>
        <div id="container">
              <div id="login_container">
                  <form action="" method="POST">
                      {% csrf_token %}
                      <fieldset class ="login_form">
                          <legend class="blind">로그인</legend>
                          <div class="id_area">
                              <div class="input_row" id="id_area">
                                  <span class="input_box">
                                      <input type="text" class="input_form"id={{form.username.id_for_label}}" maxlength="15" name="{{form.username.html_name}}" placeholder="아이디">
                                  </span>
                              </div>
                          </div>
                          <div class="pw_area">
                            <div class="input_row" id="pw_area">
                                <span class="input_box">
                                    <input type="password" class="input_form" id="{{form.password.id_for_label}}" name="{{form.password.html_name}}" placeholder="비밀번호" >
                                </span>
                            </div>
                          </div>
                          <input type="submit" title="로그인" value="로그인" class="btn_login">
                      </fieldset>
                  </form>
                  <div class="signup">
                      <a target="_blank" id="join" href="{%url 'accounts:signup' %}">회 원 가 입</a>
                  </div>
              </div>
        </div>

        <div id="footer">
              <ul>
                  <li>
                      <a target="_blank" href="http://www.naver.com/rules/service.html" id="fot.agreement">이용약관</a>
                  </li>
                  <li>
                      <strong>
                      <a target="_blank" href="http://www.naver.com/rules/privacy.html" id="fot.privacy">개인정보처리방침</a>
                      </strong>
                  </li>
                  <li>
                      <a target="_blank" href="http://www.naver.com/rules/disclaimer.html" id="fot.disclaimer">책임의 한계와 법적고지</a>
                  </li>
                  <li>
                      <a target="_blank" href="https://help.naver.com/support/service/main.nhn?serviceNo=532" id="fot.help">회원정보 고객센터</a>
                  </li>
              </ul>
              <div class="copyright">
                  <p>
                      <span>Copyright</span>
                      ©
                      <a href="https://www.navercorp.com/" target="_blank">NAVER Corp.</a>
                      <span>All Rights Reserved.</span>
                  </p>
              </div>
        </div>
    </div>

  </body>
</html>

LeeDongu/merge_login/accounts/templates/accounts/login_fail.html
{% extends "accounts/layout.html" %}

{% block content %}
<!-- 로그인 실패 화면이 들어올 영역 -->
<div id="container">
      <div id="login_container">
          <div class="fail_message">
              <h2> 로그인에 실패하셨습니다.</h2>
              </br>
              <p>아이디가 없다면 <br> 회원가입을 해주세요</p>
              <div class="signup">
                  아이디가 없으신가요?<a href="{%url 'accounts:signup' %}">회 원 가 입</a>
              </div>
          </div>
      </div>
</div>
{% endblock %}

LeeDongu/merge_login/accounts/templates/accounts/signup.html
{% extends "accounts/layout.html" %}

{% block content %}
<!-- 회원가입 화면이 들어올 영역 -->
<div id="main_container">
        <div class="form_container">
            <div class="form">
                <form action="#" method="post">
                    {% csrf_token %} <!-- 폼데이터가 전송 될 때마다 임의의 문자열을 생성해 자체 인증 보안 강화 기술 -->
                        {{form.as_p}} <!-- 폼과 연결된 필드의 값을 입력 할 수 있도록 html 코드를 자동으로 생성 -->
                    <input type="submit" id="submit_btn" value="회원가입" class="submit_btn">
                </form>
            </div>
            <div class="bottom_box">
                <div class="no_id">
                    <span><br>아이디가 있다면 </span><a href="{% url 'accounts:login' %}">로그인</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

LeeDongu/merge_login/config/templates/layout.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
      {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/login_layout.css' %}">
    <title></title>
  </head>
  <body>
  {%load static%}
    <div id="wrap">
        <div id="header">
            <div id="header_box">
                <a href="#" class="header_img" id="log.naver"><img src="{% static 'image/d2_logo.png'%}"></a>
            </div>
        </div>
        <!-- 각기 다른 content -->
        {% block content %}
        {% endblock %}

        <div id="footer">
              <ul>
                  <li>
                      <a target="_blank" href="http://www.naver.com/rules/service.html" id="fot.agreement">이용약관</a>
                  </li>
                  <li>
                      <strong>
                      <a target="_blank" href="http://www.naver.com/rules/privacy.html" id="fot.privacy">개인정보처리방침</a>
                      </strong>
                  </li>
                  <li>
                      <a target="_blank" href="http://www.naver.com/rules/disclaimer.html" id="fot.disclaimer">책임의 한계와 법적고지</a>
                  </li>
                  <li>
                      <a target="_blank" href="https://help.naver.com/support/service/main.nhn?serviceNo=532" id="fot.help">회원정보 고객센터</a>
                  </li>
              </ul>
              <div class="copyright">
                  <p>
                      <span>Copyright</span>
                      ©
                      <a href="https://www.navercorp.com/" target="_blank">NAVER Corp.</a>
                      <span>All Rights Reserved.</span>
                  </p>
              </div>
        </div>
    </div>

  </body>
</html>