IncheonYSH/django project/board/urls.py
from django.urls import path
from django.urls import include
from board import views
from .views import article
from .views import write

app_name = 'board'

urlpatterns = [
    path('article/<int:article_num>', views.article, name='article'),
    path('write', views.write, name='write'),
    path('modify/<int:article_num>', views.modify, name='modify'),
    path('delete/<int:article_num>', views.delete, name='delete'),
    path('write_comment/<int:article_num>', views.write_comment, name='write_comment'),
    path('delete_comment/<int:comment_num>', views.delete_comment, name='delete_comment'),
    path('like/article/<int:article_num>', views.like_article, name='like_article'),
    path('dislike/article/<int:article_num>', views.dislike_article, name='dislike_article'),
    path('', views.index, name='index'),
]

IncheonYSH/django project/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('board/', include('board.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

IncheonYSH/django project/board/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Article(models.Model):
    article_number = models.AutoField(primary_key=True)
    username = models.ForeignKey(User, on_delete=models.DO_NOTHING, db_column='username', related_name='username_article')
    title = models.CharField(max_length=30)
    maintext = models.TextField()
    time = models.DateTimeField(auto_now_add=True, auto_now=False)
    viewcount = models.PositiveIntegerField(default=0)
    like = models.ManyToManyField(User, related_name='like_article')
    dislike = models.ManyToManyField(User, related_name='dislike_article')
    def __str__(self):
        return str(self.article_number)
    @property
    def update_counter(self):
        self.viewcount = self.viewcount + 1
        self.save()



class Comment(models.Model):
    comment_number = models.AutoField(primary_key=True)
    article_number = models.ForeignKey(Article, on_delete=models.CASCADE, db_column='article_number')
    commentcomment_number = models.IntegerField(blank=True, null=True)
    username = models.ForeignKey(User, on_delete=models.DO_NOTHING, db_column='username')
    comment = models.CharField(max_length=500)
    time = models.DateTimeField(auto_now_add=True, auto_now=False)
    def __str__(self):
        return str(self.comment_number)

IncheonYSH/django project/board/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from .models import Article
from .models import Comment

class WriteArticleForm(forms.ModelForm):
    title = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': '제목을 입력하세요'}))
    maintext = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Article
        fields = ['title', 'maintext',]

class CommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=500, widget=forms.Textarea)
    class Meta:
        model = Comment
        fields = ['comment',]

IncheonYSH/django project/board/views.py
from django.shortcuts import render
from .forms import WriteArticleForm
from .forms import CommentForm
from board.models import Article
from board.models import Comment
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.paginator import Paginator
from django.utils.html import strip_tags
import markdown
from markdownify import markdownify


# article list
def index(request):
    page = request.GET.get('page', 1)
    article_list = Article.objects.all().order_by('-article_number')
    paginator = Paginator(article_list, 20)
    page_obj = paginator.get_page(page)
    context = {'article_list': page_obj}
    return render(request, 'board/list.html', context)

# Request article, comment
def article(request, article_num):
    try:
        article_objects = Article.objects.get(article_number=article_num)
    except:
        article_objects = None

    try:
        comment_objects = Comment.objects.filter(article_number=article_num).order_by('comment_number')
    except:
        comment_objects = None

    article_objects.maintext = markdown.markdown(article_objects.maintext,
                                                 extensions=[
                                                     'markdown.extensions.extra',
                                                     'markdown.extensions.codehilite',
                                                     'markdown.extensions.toc',
                                                 ])
    comment_form = CommentForm()
    context = {
        'article_objects': article_objects,
        'comment_objects': comment_objects,
        'comment_form': comment_form,
    }
    return render(request, 'board/article.html', context)

# Create comment
@login_required(login_url='/accounts/login')
def write_comment(request, article_num):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.username = request.user
        comment.article_number = Article(article_number=article_num)
        comment.save()
    return redirect('board:article', article_num=article_num)

# Delete comment
@login_required(login_url='/accounts/login')
def delete_comment(request, comment_num):
    comment = get_object_or_404(Comment, pk=comment_num)
    if request.user != comment.username:
        messages.error(request, '권한없음')
        return redirect('board:article', article_num=comment.article_number)

    else:
        comment.delete()
    return redirect('board:article', article_num=comment.article_number)

# Create article
@login_required(login_url='/accounts/login')
def write(request):
    if request.method == 'POST':
        form = WriteArticleForm(request.POST)
        if form.is_valid():
            article_write = form.save(commit=False)
            article_write.username = request.user
            article_write.save()
            return redirect('/board')
    else:
        form = WriteArticleForm()
    return render(request, 'board/write.html', {"form": form})

# Update article
@login_required(login_url='/accounts/login')
def modify(request, article_num):
    article = get_object_or_404(Article, pk=article_num)
    article.maintext = markdownify(article.maintext)
    if request.user != article.username:
        messages.error(request, '권한없음')
        return redirect('board:article', article_num=article.article_number)

    if request.method == "POST":
        form = WriteArticleForm(request.POST, instance=article)
        if form.is_valid():
            article = form.save(commit=False)
            article.username = request.user
            article.save()
            return redirect('board:article', article_num=article.article_number)

    else:
        form = WriteArticleForm(instance=article)
    context = {'form': form}
    return render(request, 'board/modify.html', context)

# Delete article
@login_required(login_url='/accounts/login')
def delete(request, article_num):
    article = get_object_or_404(Article, pk=article_num)
    if request.user != article.username:
        messages.error(request, '권한없음')
        return redirect('board:article', article_num=article.article_number)
    article.delete()
    return redirect('board:index')

# Like
@login_required(login_url='/accounts/login')
def like_article(request, article_num):
    article = get_object_or_404(Article, pk=article_num)
    article.like.add(request.user)
    return redirect('board:article', article_num=article.article_number)

# Dislike
@login_required(login_url='/accounts/login')
def dislike_article(request, article_num):
    article = get_object_or_404(Article, pk=article_num)
    article.dislike.add(request.user)
    return redirect('board:article', article_num=article.article_number)

IncheonYSH/django project/templates/board/article.html
{% load static %}
{{ article_objects.update_counter }}
{% load board_filter %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>clone</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/community_layout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/menu.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/darcula.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/article_detail.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/community_banner.css' %}">
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/slideShow.js' %}"></script>
    <script src="{% static 'js/upbtn.js' %}"></script>
    <script type="text/javascript">
    </script>
    {% if messages %}
        {% for message in messages %}
           {% if message.tags %}
            <script>alert("{{ message }}")</script>
            {% endif %}
        {% endfor %}
    {% endif %}
</head>
<body>
    <div id="wrap">
        <div id="header">
            <div class="headerBox">
                <div class="headerLimit">
                    <div class="inner_header">
                        <div class="logoBox"><a href="{% url 'home' %}"><img src="{% static 'image/d2.png' %}" id="logoImg"></a></div>
                        <div class="topMenuBox">
                            <div style="height : 0px; transition: all 0.5s ease 0s;">
                              <ul>
                                  <li>
                                      <a href="#">HelloWorld</a>
                                  </li>
                                  <li>
                                      <a href="#">D2 News</a>
                                  </li>
                                  <li>
                                      <a href="#">D2 Program</a>
                                  </li>
                                  <li>
                                      <a href="#">About D2</a>
                                  </li>
                                  <li>
                                      <a href="/board">Community</a>
                                  </li>
                              </ul>
                            </div>
                        </div>
                        <div class="searchBar">
                            <legend>검색</legend>
                            <form action = "/">
                                <input type="text" value placeholder="D2에서 검색" class="search_area">
                                <button type="submit" class="btn_search"><img src="{% static 'image/search.png' %}"> </button>
                            </form>
                        </div>
                        <div class="login">
                            <ul>
                                <li>
                                    {% if user.is_authenticated %}
                                    <a href="{% url 'logout' %}">Logout</a>
                                    {% else %}
                                    <a href="{% url 'login' %}">Login</a>
                                    {% endif %}
                                </li>
                            </ul>
                        </div>
                  </div>
                </div>
            </div>
        </div>
        <div id="slideBox">
            <div class = "banner">
                <span class = "banner_title">Community</span>
                <span class = "banner_split">|</span>
                <span class = "banner_meta">정보 공유 및 소통을 위한 커뮤니티입니다.</span>
            </div>
        </div>
        <div id="mainBox">
            <div id = "body_main">
                {% if article_objects %}
                    <div id="container_article">
                        <!-- single_article_metadata -->
                        <div class = "contents">
                            <div class = "content_post">
                                <div class = "content_post_inner">
                                    <div class = "title">
                                        {{ article_objects.title }}
                                    </div>
                                    <div class="doc_info">
                                        <span class = "icon">
                                            <i class="fas fa-user-edit"></i>
                                        </span>
                                        <span class = "article_writer">{{ article_objects.username }}</span>
                                        <span class = "doc_info_split">|</span>
                                        <span class = "icon">
                                            <i class = "far fa-clock fa-xs"></i>
                                        </span>
                                        <span class = "upload_date">{{ article_objects.time|date:"Y.m.d" }}</span>
                                        <span class = "doc_info_split">|</span>
                                        <span class = "icon">
                                            <i class = "far fa-eye xs"></i>
                                        </span>
                                        <span class = "view_count"></span>{{ article_objects.viewcount }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!---->
                    </div>
                <div class = "main_text">
                    {{ article_objects.maintext|safe }}
                </div>
                <div class = "comment_box">
                    {% if comment_objects %}
                        {% for comment in comment_objects %}
                            <div class = "comment_container">
                                <div class = "comment">
                                    {{ comment.comment }}
                                </div>
                                <span class = "delete_comment" onclick = "location.href='{% url 'board:delete_comment' comment.comment_number %}'">
                                    <i class="fas fa-times"></i>
                                </span>
                                <div class = "doc_info">
                                    <span class = "icon">
                                        <i class="fas fa-user-edit"></i>
                                    </span>
                                    <span class = "comment_writer">{{ comment.username }}</span>
                                    <span class = "doc_info_split">|</span>
                                    <span class = "icon">
                                        <i class = "far fa-clock fa-xs"></i>
                                    </span>
                                    <span class = "upload_date">{{ comment.time|date:"Y.m.d" }}</span>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                    {% endif %}
                    <div class = "form_container">
                        <form method="post" action="{% url 'board:write_comment' article_objects.article_number %}">
                            {%csrf_token%}
                            {{comment_form.comment}}
                            <input class = "submit_comment" type = "submit" value = "등록">
                        </form>
                    </div>
                </div>
                <div class = "article_buttons">
                    <span class="board_list" onclick = "location.href={% url 'board:index' %}">전체글</span>
                    {% if request.user == article_objects.username %}
                        <span class="board_delete" onclick = "location.href='{% url 'board:delete' article_objects.article_number %}'">
                            삭제
                        </span>
                        <span class="board_modify" onclick = "location.href='{% url 'board:modify' article_objects.article_number %}'">
                            수정
                        </span>
                    {% endif %}
                </div>

                {% else %}
                    <div class = 'deleted'>삭제된 게시글입니다</div>
                {% endif %}
            </div>
        </div>

        <footer>
            <div id="footer">
                <div id="big_footer" class="big_footer ">
                    <div class="footer_up">
                        <ul class="other_site">
                            <li><a href="https://developers.naver.com" target="_blank"><img src="{% static 'image/naverdev.png' %}"></a></li>
                            <li><a href="https://techcon.naver.com" target="_blank"><img src="{% static 'image/ntc.png' %}"></a></li>
                            <li><a href="https://deview.kr" target="_blank"><img src="{% static 'image/DEVIEW.png' %}"></a></li>
                            <li><a href="https://naver.github.io" target="_blank"><img src="{% static 'image/OpenSource.png' %}"></a></li>
                            <li><a href="https://www.d2startup.com" target="_blank"><img src="{% static 'image/d2start.png' %}"></a></li>
                        </ul>
                        <div class="sns_share">
                            <ul>
                                <li class="email">
                                    <a href="#"><img src="{% static 'image/email.png' %}"></a>
                                </li>
                                <li class="facebook">
                                    <a href="#"><img src="{% static 'image/facebook.png' %}"></a>
                                </li>
                                <li class="rss">
                                    <a href="#"><img src="{% static 'image/rss.png' %}"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="footer_down">
                        <div class="copyright">
                            <p>
                                <span>Copyright</span>
                                ©
                                <a href="https://www.navercorp.com/" target="_blank">NAVER Corp.</a>
                                <span>All Rights Reserved.</span>
                            </p>
                            <a href="#" class="btn_go_top" id="btn_go_top" style="bottom : 20px; right:0px;" ><img src="{% static 'image/btn_up.png' %}"></a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</body>
</html>

IncheonYSH/django project/templates/board/list.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>clone</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/community_layout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/menu.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/article_list.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/community_banner_main.css' %}">
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/slideShow.js' %}"></script>
    <script src="{% static 'js/upbtn.js' %}"></script>
    <script type="text/javascript">
    </script>
</head>
<body>
    <div id="wrap">
        <div id="header">
            <div class="headerBox">
                <div class="headerLimit">
                    <div class="inner_header">
                        <div class="logoBox"><a href="{% url 'home' %}"><img src="{% static 'image/d2.png' %}" id="logoImg"></a></div>
                        <div class="topMenuBox">
                            <div style="height : 0px; transition: all 0.5s ease 0s;">
                              <ul>
                                  <li>
                                      <a href="#">HelloWorld</a>
                                  </li>
                                  <li>
                                      <a href="#">D2 News</a>
                                  </li>
                                  <li>
                                      <a href="#">D2 Program</a>
                                  </li>
                                  <li>
                                      <a href="#">About D2</a>
                                  </li>
                                  <li>
                                      <a href="/board">Community</a>
                                  </li>
                              </ul>
                            </div>
                        </div>
                        <div class="searchBar">
                            <legend>검색</legend>
                            <form action = "/">
                                <input type="text" value placeholder="D2에서 검색" class="search_area">
                                <button type="submit" class="btn_search"><img src="{% static 'image/search.png' %}"> </button>
                            </form>
                        </div>
                        <div class="login">
                            <ul>
                                <li>
                                    {% if user.is_authenticated %}
                                    <a href="{% url 'logout' %}">Logout</a>
                                    {% else %}
                                    <a href="{% url 'login' %}">Login</a>
                                    {% endif %}
                                </li>
                            </ul>
                        </div>
                  </div>
                </div>
            </div>
        </div>
        <div id="slideBox">
            <div class = "banner">
                <span class = "banner_title">Community</span>
                <span class = "banner_split">|</span>
                <span class = "banner_meta">정보 공유 및 소통을 위한 커뮤니티입니다.</span>
            </div>
        </div>
        <div id="mainBox">
            <div id = "body_main">
                <!-- article_list -->
                <div id="container_article">
                    {% if article_list %}
                        {% for article in article_list %}
                        <!-- single_article -->
                        <div class = "contents">
                            <div class = "content_post">
                                <div class = "content_post_inner">
                                    <div class = "title" onclick = "location.href='/board/article/{{ article.article_number }}'">
                                        {{ article.title }}
                                    </div>
                                    <div class="doc_info">
                                        <span class = "icon">
                                            <i class="fas fa-user-edit"></i>
                                        </span>
                                        <span class = "article_writer">{{ article.username }}</span>
                                        <span class = "doc_info_split">|</span>
                                        <span class = "icon">
                                            <i class = "far fa-clock fa-xs"></i>
                                        </span>
                                        <span class = "upload_date">{{ article.time|date:"Y.m.d" }}</span>
                                        <span class = "doc_info_split">|</span>
                                        <span class = "icon">
                                            <i class = "far fa-eye xs"></i>
                                        </span>
                                        <span class = "view_count"></span>{{ article.viewcount }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!---->
                        {% endfor %}
                    {% else %}
                    {% endif %}
                </div>
                <!---->
                <span id = "write_button" onclick = "location.href='{% url 'board:write' %}'">
                    글쓰기
                </span>
                <!-- page_number -->
                <div id = "page">
                    {% if article_list.has_previous %}
                    <span class = "page_num" onclick = "location.href='?page={{ article_list.previous_page_number }}'">🡠</span>
                    {% else %}
                    {% endif %}
                    {% for page_number in article_list.paginator.page_range %}
                    {% if page_number >= article_list.number|add:-2 and page_number <= article_list.number|add:2 %}
                        {% if page_number == article_list.number %}
                        <span class = "page_num_active" onclick = "location.href='?page={{ page_number }}'">
                            {{ page_number }}
                        </span>
                        {% else %}
                        <span class = "page_num" onclick = "location.href='?page={{ page_number }}'">
                            {{ page_number }}
                        </span>
                        {% endif %}
                    {% endif %}
                    {% endfor %}
                    {% if article_list.has_next %}
                    <span class = "page_num" onclick = "location.href='?page={{ article_list.next_page_number }}'">🡢</span>
                    {% else %}
                    {% endif %}
                </div>

            </div>
        </div>

        <footer>
            <div id="footer">
                <div id="big_footer" class="big_footer ">
                    <div class="footer_up">
                        <ul class="other_site">
                            <li><a href="https://developers.naver.com" target="_blank"><img src="{% static 'image/naverdev.png' %}"></a></li>
                            <li><a href="https://techcon.naver.com" target="_blank"><img src="{% static 'image/ntc.png' %}"></a></li>
                            <li><a href="https://deview.kr" target="_blank"><img src="{% static 'image/DEVIEW.png' %}"></a></li>
                            <li><a href="https://naver.github.io" target="_blank"><img src="{% static 'image/OpenSource.png' %}"></a></li>
                            <li><a href="https://www.d2startup.com" target="_blank"><img src="{% static 'image/d2start.png' %}"></a></li>
                        </ul>
                        <div class="sns_share">
                            <ul>
                                <li class="email">
                                    <a href="#"><img src="{% static 'image/email.png' %}"></a>
                                </li>
                                <li class="facebook">
                                    <a href="#"><img src="{% static 'image/facebook.png' %}"></a>
                                </li>
                                <li class="rss">
                                    <a href="#"><img src="{% static 'image/rss.png' %}"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="footer_down">
                        <div class="copyright">
                            <p>
                                <span>Copyright</span>
                                ©
                                <a href="https://www.navercorp.com/" target="_blank">NAVER Corp.</a>
                                <span>All Rights Reserved.</span>
                            </p>
                            <a href="#" class="btn_go_top" id="btn_go_top" style="bottom : 20px; right:0px;" ><img src="{% static 'image/btn_up.png' %}"></a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</body>
</html>